[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn alhassan.wsgi:application --bind 0.0.0.0:$PORT"
releaseCommand = "python manage.py migrate && python manage.py collectstatic --noinput"
healthcheckPath = "/"
healthcheckTimeout = 120
